### ISSUE TITLE
1.16.5 Crash

### ISSUE THREAD

**Issue by AmyRose1288** [MehVahdJukaar/Randomium#5]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 1/17/22 4:51 PM
Description: Initializing game

java.lang.ArithmeticException: / by zero
	at net.mehvahdjukaar.randomium.items.AnyItem.func_77658_a(AnyItem.java:19) ~[?:1.16.5-1.7] {re:classloading}
	at net.minecraft.item.Item.func_77667_c(Item.java:179) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:crossbows.8,re:mixin,pl:accesstransformer:B,xf:fml:forge:crossbows.8}
	at net.minecraft.item.Item.func_200295_i(Item.java:227) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:crossbows.8,re:mixin,pl:accesstransformer:B,xf:fml:forge:crossbows.8}
	at net.minecraft.item.ItemStack.func_200301_q(ItemStack.java:528) ~[?:?] {re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack,re:mixin,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack}
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:565) ~[?:?] {re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack,re:mixin,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack}
	at net.minecraft.client.Minecraft.func_213251_b(Minecraft.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:inventorypause.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$5566/1712158903.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:36) ~[?:?] {re:classloading,xf:fml:jecharacters:jecharacters-gen73,xf:fml:jecharacters:jecharacters-gen74}
	at net.minecraft.client.util.SearchTreeReloadable.func_217872_a(SourceFile:48) ~[?:?] {re:classloading,xf:fml:jecharacters:jecharacters-gen75,xf:fml:jecharacters:jecharacters-gen76}
	at net.minecraft.client.Minecraft.lambda$createSearchTrees$10(Minecraft.java:660) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:inventorypause.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$5572/333976730.accept(Unknown Source) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51] {}
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:659) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:inventorypause.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:476) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:inventorypause.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.20.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$494/716141396.call(Unknown Source) [forge-1.16.5-36.2.20.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.mehvahdjukaar.randomium.items.AnyItem.func_77658_a(AnyItem.java:19) ~[?:1.16.5-1.7] {re:classloading}
	at net.minecraft.item.Item.func_77667_c(Item.java:179) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:crossbows.8,re:mixin,pl:accesstransformer:B,xf:fml:forge:crossbows.8}
	at net.minecraft.item.Item.func_200295_i(Item.java:227) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:crossbows.8,re:mixin,pl:accesstransformer:B,xf:fml:forge:crossbows.8}
	at net.minecraft.item.ItemStack.func_200301_q(ItemStack.java:528) ~[?:?] {re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack,re:mixin,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack}
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:565) ~[?:?] {re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack,re:mixin,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack}
	at net.minecraft.client.Minecraft.func_213251_b(Minecraft.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:inventorypause.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$5566/1712158903.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:36) ~[?:?] {re:classloading,xf:fml:jecharacters:jecharacters-gen73,xf:fml:jecharacters:jecharacters-gen74}
	at net.minecraft.client.util.SearchTreeReloadable.func_217872_a(SourceFile:48) ~[?:?] {re:classloading,xf:fml:jecharacters:jecharacters-gen75,xf:fml:jecharacters:jecharacters-gen76}
	at net.minecraft.client.Minecraft.lambda$createSearchTrees$10(Minecraft.java:660) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:inventorypause.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$5572/333976730.accept(Unknown Source) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51] {}
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:659) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:inventorypause.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:476) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:inventorypause.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.20.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$494/716141396.call(Unknown Source) [forge-1.16.5-36.2.20.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 407877568 bytes (388 MB) / 1737490432 bytes (1657 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 12
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.20.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.20
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		secondchanceforge-1.2.0.jar                       |Second Chance Forge           |secondchanceforge             |1.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		GokiStats-1.16.5-1.3.0.jar                        |Goki Stats                    |gokistats                     |1.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		JustEnoughAdvancements-1.16.5-1.0.2.jar           |Just Enough Advancements      |jea                           |1.16.5-1.0.2        |COMMON_SET|Manifest: NOSIGNATURE
		potiondescriptions-1.16.5-1.5.3.jar               |Potion Descriptions           |potiondescriptions            |1.16.5-1.5.3        |COMMON_SET|Manifest: NOSIGNATURE
		BetterF3-1.1.3-forge-1.16.5.jar                   |BetterF3 Forge                |betterf3forge                 |1.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		beenfo-1.16.4-forge35.0.7-1.2.jar                 |Beenfo                        |beenfo                        |1.16.4-forge35.0.7-1|COMMON_SET|Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.145.jar                          |Just Enough Items             |jei                           |7.7.1.145           |COMMON_SET|Manifest: NOSIGNATURE
		prefab-1.6.5.15.jar                               |Prefab                        |prefab                        |1.6.5.15            |COMMON_SET|Manifest: NOSIGNATURE
		AttributeFix-1.16.5-10.1.3.jar                    |AttributeFix                  |attributefix                  |10.1.3              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		DoggyTalents-1.16.5-2.1.15.jar                    |Doggy Talents 2               |doggytalents                  |2.1.15              |COMMON_SET|Manifest: NOSIGNATURE
		ProjectE-1.16.5-PE1.0.1B.jar                      |ProjectE                      |projecte                      |PE1.0.1B            |COMMON_SET|Manifest: NOSIGNATURE
		torohealth-1.16.4-forge-4.jar                     |ToroHealth                    |torohealth                    |NONE                |COMMON_SET|Manifest: NOSIGNATURE
		BowInfinityFix-1.16.x-rv9.1.jar                   |Bow Infinity Fix              |bowinfinityfix                |rv9.1               |COMMON_SET|Manifest: NOSIGNATURE
		Neat 1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |COMMON_SET|Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.4.jar                        |Waystones                     |waystones                     |7.6.4               |COMMON_SET|Manifest: NOSIGNATURE
		shutupexperimentalsettings-1.0.3.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.16.5-5.7.3.jar                       |Journeymap                    |journeymap                    |5.7.3               |COMMON_SET|Manifest: NOSIGNATURE
		CTM-MC1.16.1-1.1.2.6.jar                          |ConnectedTexturesMod          |ctm                           |MC1.16.1-1.1.2.6    |COMMON_SET|Manifest: NOSIGNATURE
		Controlling-7.0.0.28.jar                          |Controlling                   |controlling                   |7.0.0.28            |COMMON_SET|Manifest: NOSIGNATURE
		configured-1.5.1-1.16.5.jar                       |Configured                    |configured                    |1.5.1               |COMMON_SET|Manifest: NOSIGNATURE
		LibX-1.16.3-1.0.76.jar                            |LibX                          |libx                          |1.16.3-1.0.76       |COMMON_SET|Manifest: NOSIGNATURE
		projectex-1605.2.0-build.3.jar                    |ProjectEX                     |projectex                     |1605.2.0-build.3    |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.4.31.jar                |Bookshelf                     |bookshelf                     |10.4.31             |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Tips-1.16.5-4.0.15.jar                            |Tips                          |tips                          |4.0.15              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		guardvillagers-1.16.5.1.2.6.jar                   |Guard Villagers               |guardvillagers                |1.2.6               |COMMON_SET|Manifest: NOSIGNATURE
		cheat_mode-1.16.X-1.2.3.jar                       |Cheat Mode Mod                |cheat_mode                    |1.2.3               |COMMON_SET|Manifest: NOSIGNATURE
		ChanceCubes-1.16.5-5.0.2.433.jar                  |Chance Cubes                  |chancecubes                   |1.16.5-5.0.2.433    |COMMON_SET|Manifest: NOSIGNATURE
		potionstacker_1.16.5-1.0.jar                      |Potion Stacker Mod            |potionstacker                 |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		jeed-1.16.5-1.6.jar                               |Just Enough Effect Description|jeed                          |1.16.5-1.6          |COMMON_SET|Manifest: NOSIGNATURE
		ExplorersCompass-1.16.5-1.1.2-forge.jar           |Explorer's Compass            |explorerscompass              |1.16.5-1.1.2-forge  |COMMON_SET|Manifest: NOSIGNATURE
		clickadv-2.0.jar                                  |clickadv mod                  |clickadv                      |2.0                 |COMMON_SET|Manifest: NOSIGNATURE
		catalogue-1.5.0-1.16.5.jar                        |Catalogue                     |catalogue                     |1.5.0               |COMMON_SET|Manifest: NOSIGNATURE
		randomium-1.16.5-1.7.jar                          |Randomium                     |randomium                     |1.16.5-1.7          |COMMON_SET|Manifest: NOSIGNATURE
		JustEnoughResources-1.16.5-0.12.1.133.jar         |Just Enough Resources         |jeresources                   |0.12.1.133          |COMMON_SET|Manifest: NOSIGNATURE
		Exp Ore Mod - 1.16.5 - 1.3.jar                    |Exp Ore Block                 |exp_ore                       |1.3                 |COMMON_SET|Manifest: NOSIGNATURE
		Wandering-Bag-1.16.5-1.0.2.jar                    |Wandering Bag                 |wandering_bag                 |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		Uncrafter-1.16.5-1.0.0.jar                        |Uncrafter                     |uncrafter                     |1.16.5-1.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		restored_earth-1.16.5-1.4.0.jar                   |Restored Earth                |restored_earth                |1.4.0               |COMMON_SET|Manifest: NOSIGNATURE
		ninjaphenix-container-library-1.2.10+1.16.5.jar   |NinjaPhenix's Container Librar|ninjaphenix_container_lib     |1.2.10              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.20-universal.jar                |Forge                         |forge                         |36.2.20             |COMMON_SET|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		mineralchance_1.16.5-1.6.jar                      |Mineral Chance                |mineralchance                 |1.6                 |COMMON_SET|Manifest: NOSIGNATURE
		MmmMmmMmmMmm-1.16.5-1.3.1.jar                     |MmmMmmMmmMmm                  |dummmmmmy                     |1.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		EquipmentCompare-1.16.5-1.2.7.jar                 |Equipment Compare             |equipmentcompare              |1.2.7               |COMMON_SET|Manifest: NOSIGNATURE
		CraftingTweaks_1.16.5-12.2.1.jar                  |Crafting Tweaks               |craftingtweaks                |12.2.1              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.20-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |COMMON_SET|Manifest: NOSIGNATURE
		EnchantmentDescriptions-1.16.5-7.0.18.jar         |EnchantmentDescriptions       |enchdesc                      |7.0.18              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |COMMON_SET|Manifest: NOSIGNATURE
		visiblearmorslots-2.0-1.16.5.jar                  |Visible Armor Slots           |visiblearmorslots             |2.0-1.16.5          |COMMON_SET|Manifest: NOSIGNATURE
		Jade-1.16.4-2.8.1.jar                             |Jade                          |jade                          |2.8.1               |COMMON_SET|Manifest: NOSIGNATURE
		StumbleUponCampsites.jar                          |StumbleUponCamps              |stumbleuponcamps              |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Highlighter-1.16.5-1.1.1.jar                      |Highlighter                   |highlighter                   |1.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		jeiintegration_1.16.5-7.0.1.15.jar                |JEI Integration               |jeiintegration                |7.0.1.15            |COMMON_SET|Manifest: NOSIGNATURE
		Iceberg-1.16.5-1.0.38.jar                         |Iceberg                       |iceberg                       |1.0.38              |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.2.jar                         |Patchouli                     |patchouli                     |1.16.4-53.2         |COMMON_SET|Manifest: NOSIGNATURE
		armorpointspp-1.16.5-2.0.0.jar                    |ArmorPoints++                 |armorpointspp                 |1.16.5-2.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		randomite-1.16.4-1.0.1.jar                        |Randomite Classic             |randomite                     |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.16.5-3.8.jar                         |Collective                    |collective                    |3.8                 |COMMON_SET|Manifest: NOSIGNATURE
		Explosiont-1.16.5-2.4.4.jar                       |Explosion't                   |explosiont                    |1.16.5-2.4.4        |COMMON_SET|Manifest: NOSIGNATURE
		polymorph-forge-1.16.5-0.39.jar                   |Polymorph                     |polymorph                     |1.16.5-0.39         |COMMON_SET|Manifest: NOSIGNATURE
		JustEnoughProfessions-1.16.5-1.2.2.jar            |Just Enough Professions (JEP) |justenoughprofessions         |1.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		torcherino-14.0.0+1.16.4.jar                      |Torcherino                    |torcherino                    |14.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		OreExcavation-1.8.157.jar                         |Ore Excavation                |oreexcavation                 |1.8.157             |COMMON_SET|Manifest: e7:68:1c:0d:b9:7e:cf:f8:f3:40:9c:84:c5:39:d7:a4:59:78:b0:6b:c3:fd:b7:4f:69:18:a3:88:e3:76:8c:3f
		JustEnoughCharacters-1.16.4-4.3.2.jar             |Just Enough Characters        |jecharacters                  |1.16.4-4.3.2        |COMMON_SET|Manifest: NOSIGNATURE
		InventoryHud_[1.16.2-1.16.5].forge-3.4.1.jar      |Inventory HUD+(Forge edition) |inventoryhud                  |3.4.1               |COMMON_SET|Manifest: NOSIGNATURE
		IKnowWhatImDoing-3.2.0-forge.jar                  |I Know What I'm Doing         |iknowwhatimdoing              |3.2.0               |COMMON_SET|Manifest: 42:2c:5e:4c:e2:f5:d1:07:7f:aa:29:ae:31:88:80:0c:b1:a6:87:6b:6a:2d:0f:67:57:e4:5a:4a:26:73:31:ac
		thevanillaexperience_1.16.5-1.4.jar               |The Vanilla Experience        |thevanillaexperience          |1.4                 |COMMON_SET|Manifest: NOSIGNATURE
		expandedstorage-7.3.8+1.16.5.jar                  |Expanded Storage              |expandedstorage               |7.3.8               |COMMON_SET|Manifest: NOSIGNATURE
		InventoryProfilesNext-forge-1.16-1.2.3.jar        |Inventory Profiles Next       |inventoryprofilesnext         |1.2.3               |COMMON_SET|Manifest: NOSIGNATURE
		HunterIllager-1.16.5-1.4.0.jar                    |Hunter Illager                |hunterillager                 |1.16.5-1.4.0        |COMMON_SET|Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.2.0.jar                |AppleSkin                     |appleskin                     |mc1.16.4-2.2.0      |COMMON_SET|Manifest: NOSIGNATURE
		UndergroundCrates_1.16.5-1.3.1.jar                |Underground Crates            |dungeoncrates                 |1.3.1               |COMMON_SET|Manifest: NOSIGNATURE
		extendedcreativeinventory_1.16.5-1.6.jar          |Extended Creative Inventory   |extendedcreativeinventory     |1.6                 |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-4.13.49-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.13.49             |COMMON_SET|Manifest: NOSIGNATURE
		PuzzlesLib-v1.0.15-1.16.5-Forge.jar               |Puzzles Lib                   |puzzleslib                    |1.0.15              |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		JustEnoughEffects-1.1.2.jar                       |Just Enough Effects           |effectinfo                    |1.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		illagers_plus-1.16.4v1.7.2.jar                    |Illagers+                     |illagers_plus                 |1.16.4v1.7.2        |COMMON_SET|Manifest: NOSIGNATURE
		inventorypause-mc1.16.5_v0.7.1.jar                |Inventory Pause               |inventorypause                |mc1.16.5_v0.7.1     |COMMON_SET|Manifest: NOSIGNATURE
		Babel-1.0.5.jar                                   |Babel                         |babel                         |1.0.5               |COMMON_SET|Manifest: NOSIGNATURE
		JEPB-1.0.0.jar                                    |Just Enough Piglin Bartering  |jepb                          |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		GameMenuModOption-1.16.4-1.8.2.jar                |Game Menu Mod Option          |gamemenumodoption             |1.8.2               |COMMON_SET|Manifest: NOSIGNATURE
		wwta-1.16-2.0.jar                                 |When Was That Again           |wwta                          |1.16-2.0            |COMMON_SET|Manifest: NOSIGNATURE
		EnchantingInfuser-v1.0.2-1.16.5-Forge.jar         |Enchanting Infuser            |enchantinginfuser             |1.0.2               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Cyan Warrior Swords Mod 3.3.1 (1.16.5).jar        |Cyan Warrior Swords Mod       |cwsr                          |3.3.0.0             |COMMON_SET|Manifest: NOSIGNATURE
		Cyclic-1.16.5-1.5.13.jar                          |Cyclic                        |cyclic                        |1.16.5-1.5.13       |COMMON_SET|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
	Crash Report UUID: 8e9d5f3a-293e-4831-81de-96e91ed4cb8c
	Launched Version: forge-36.2.20
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Quadro T2000/PCIe/SSE2 GL version 4.6.0 NVIDIA 472.42, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 12x Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz

**Comment by TBiscuit1** [comment]
Extended Creative Inventory is the mod that caused the crash on 1.18.1 and I'm seeing it in the pack, try removing it so it can be confirmed it's this mod that causes everything
